Add check for missing input file

diff --git a/_scripts/txt2tags2html b/_scripts/txt2tags2html
--- a/_scripts/txt2tags2html
+++ b/_scripts/txt2tags2html
@@ -57,6 +57,12 @@ comments_warning() {
     fi
 }
 
+if ! test -f "$infile"
+then
+    echo "Input file not found: $infile"
+    exit 1
+fi
+
 info "Convert to HTML"
 front_matter > "$outfile"
 clean_infile | "$txt2tags" -t html5 --no-headers -i - -o - >> "$outfile"
